services:
  - type: web
    name: salsabil-rh
    env: python
    runtime: python-3.9.18
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: SECRET_KEY
        value: 50413bec4583c16ffdc1e34242029112
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: False
    autoDeploy: true
